import type { PortfolioData } from "../data/types";
import { assetUrl, escapeHtml } from "./templates";

export function renderFallback(data: PortfolioData, reason: string): HTMLElement {
  const { profile } = data;
  const main = document.createElement("main");
  main.className = "fallback-page";
  main.id = "portfolio-content";
  main.innerHTML = `
    <div class="fallback-inner">
      <header class="fallback-header"><a class="fallback-wordmark" href="#portfolio-content">${escapeHtml(profile.name)}</a><nav aria-label="Portfolio sections"><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#experience-list">Experience</a><a href="#contact">Contact</a></nav></header>
      <section class="fallback-hero" aria-labelledby="fallback-title">
        <div><p class="eyebrow">Portfolio · ${escapeHtml(profile.location)}</p><h1 id="fallback-title" tabindex="-1">Systems that make complex work clearer.</h1><p class="fallback-lede">${escapeHtml(profile.title)}</p><p class="fallback-reason" role="status">${escapeHtml(reason)}</p><div class="fallback-actions"><a href="mailto:${escapeHtml(profile.email)}">Email Krishna</a><a href="${escapeHtml(profile.linkedin)}" target="_blank" rel="noopener noreferrer">LinkedIn <span aria-hidden="true">↗</span></a></div></div>
        <img src="${escapeHtml(assetUrl(profile.portrait))}" alt="Portrait of ${escapeHtml(profile.name)}" width="320" height="400" />
      </section>
      <section id="skills" class="fallback-section" aria-labelledby="skills-title"><div class="fallback-section-heading"><span class="eyebrow">01 / Capabilities</span><h2 id="skills-title">Four connected disciplines</h2></div><div class="fallback-list">${data.skillDomains.map((domain) => `<article data-fallback-skill><span class="fallback-index">${escapeHtml(domain.number)}</span><div><h3>${escapeHtml(domain.title)}</h3><p>${escapeHtml(domain.summary)}</p><p class="fallback-proof">${escapeHtml(domain.proof)}</p><ul class="inline-list" aria-label="Skills">${domain.skills.map((skill) => `<li>${escapeHtml(skill)}</li>`).join("")}</ul></div></article>`).join("")}</div></section>
      <section id="projects" class="fallback-section" aria-labelledby="projects-title"><div class="fallback-section-heading"><span class="eyebrow">02 / Selected work</span><h2 id="projects-title">Projects</h2><p>Eleven examples of regulatory, quality, product, and automation work.</p></div><div class="fallback-list">${data.projects.map((project) => `<article data-fallback-project id="project-${escapeHtml(project.id)}"><span class="fallback-index">${escapeHtml(project.number)}</span><div><p class="eyebrow">${escapeHtml(project.category)}</p><h3>${escapeHtml(project.title)}</h3><p class="fallback-summary">${escapeHtml(project.summary)}</p><details><summary>Read the case</summary><div class="fallback-detail"><h4>Challenge</h4><p>${escapeHtml(project.challenge)}</p><h4>Response</h4><p>${escapeHtml(project.response)}</p><h4>Outcome</h4><p>${escapeHtml(project.outcome)}</p>${project.metrics.length ? `<dl class="detail-metrics">${project.metrics.map((metric) => `<div><dt>${escapeHtml(metric.label)}</dt><dd>${escapeHtml(metric.value)}</dd></div>`).join("")}</dl>` : ""}<ul class="inline-list" aria-label="Skills">${project.skills.map((skill) => `<li>${escapeHtml(skill)}</li>`).join("")}</ul></div></details></div></article>`).join("")}</div></section>
      <section id="experience-list" class="fallback-section" aria-labelledby="experience-title"><div class="fallback-section-heading"><span class="eyebrow">03 / Career</span><h2 id="experience-title">Experience</h2></div><div class="fallback-list">${data.experience.map((role, index) => `<article data-fallback-role id="role-${escapeHtml(role.id)}"><span class="fallback-index">${String(index + 1).padStart(2, "0")}</span><div><p class="eyebrow">${escapeHtml(role.period)} · ${escapeHtml(role.location)}</p><h3>${escapeHtml(role.role)}</h3><p class="fallback-company">${escapeHtml(role.company)}</p><p>${escapeHtml(role.description)}</p><details><summary>Selected work</summary><div class="fallback-detail"><ul class="fallback-highlights">${role.highlights.map((highlight) => `<li>${escapeHtml(highlight)}</li>`).join("")}</ul><ul class="inline-list" aria-label="Skills">${role.skills.map((skill) => `<li>${escapeHtml(skill)}</li>`).join("")}</ul></div></details></div></article>`).join("")}</div></section>
      <section class="fallback-section fallback-publication" aria-labelledby="publication-title"><div><span class="eyebrow">04 / Publication</span><h2 id="publication-title">${escapeHtml(profile.publication.title)}</h2><p>A practical introduction to pharmacovigilance.</p><a href="${escapeHtml(profile.publication.url)}" target="_blank" rel="noopener noreferrer">View publication <span aria-hidden="true">↗</span></a></div><img src="${escapeHtml(assetUrl(profile.publication.cover))}" alt="Cover of ${escapeHtml(profile.publication.title)}" width="150" height="220" loading="lazy" /></section>
      <footer id="contact" class="fallback-footer"><span class="eyebrow">05 / Contact</span><h2>Let’s make the next workflow clearer.</h2><a href="mailto:${escapeHtml(profile.email)}">${escapeHtml(profile.email)}</a><a href="${escapeHtml(profile.linkedin)}" target="_blank" rel="noopener noreferrer">LinkedIn</a><p>${escapeHtml(profile.name)} · ${escapeHtml(profile.location)}</p></footer>
    </div>`;
  return main;
}
